version: '3'
services:
  db:
    image: mysql:8.0
    container_name: research_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: research_dataset
      MYSQL_USER: kkonishi
      MYSQL_PASSWORD: kkonishi
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    stdin_open: true
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    